import Head from 'next/head'
import Header from '../components/Header'
import Landing from '../components/Landing'
import { Tab } from '@headlessui/react'
import { fetchCategories } from "../utils/fetchCategories";
import { fetchProducts } from "../utils/fetchProducts";
import Product from '../components/Product';
import Basket from '../components/Basket';

export default function Home({categories,products}) {
// console.log(products);

  const showProducts = (category) => {
    
    // console.log();
    // console.log(categories[0]._id);
     return products
      .filter((product) => product.categories[0]._ref === categories[category]._id)
    .map((product) => <Product product={product} key={product._id} />); // filter products by category
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header />
    <Basket/>
    <main className="relative h-[200vh] bg-[#E7ECEE] relative" >
      <Landing />
    </main>
    <section className="relative z-[9] -mt-[100vh] min-h-screen bg-[#1B1B1B]">
    <div className="space-y-10 py-16">
          <h1 className="text-center text-4xl font-medium tracking-wide text-white md:text-5xl">
            New Promos
          </h1>
          <Tab.Group onChange={(index) => {
        console.log('Changed selected tab to:', index)
      }}>
      <Tab.List className="flex justify-center">
      {categories.map((category) => (
                <Tab
                  key={category._id}
                  id={category._id}
                  className={({ selected }) =>
                    `whitespace-nowrap rounded-t-lg py-3 px-5 text-sm font-light outline-none md:py-4 md:px-6 md:text-base ${
                      selected
                        ? "borderGradient bg-[#35383C] text-white"
                        : "border-b-2 border-[#35383C] text-[#747474]"
                    }`
                  }
                >
                  {category.title}
                </Tab>
              ))}
        {/* <Tab className="whitespace-nowrap rounded-t-lg py-3 px-5 text-sm font-light outline-none md:py-4 md:px-6 md:text-base border-b-2 border-[#35383C] text-[#747474]">Tab 1</Tab>
        <Tab className="whitespace-nowrap rounded-t-lg py-3 px-5 text-sm font-light outline-none md:py-4 md:px-6 md:text-base border-b-2 border-[#35383C] text-[#747474]">Tab 2</Tab>
        <Tab className="whitespace-nowrap rounded-t-lg py-3 px-5 text-sm font-light outline-none md:py-4 md:px-6 md:text-base border-b-2 border-[#35383C] text-[#747474]">Tab 3</Tab> */}
      </Tab.List>
      <Tab.Panels className="mx-auto max-w-fit pt-10 pb-24 sm:px-4">
      <Tab.Panel className="tabPanel">{showProducts(0)}</Tab.Panel>
       <Tab.Panel className="tabPanel">{showProducts(1)}</Tab.Panel>
        <Tab.Panel className="tabPanel">{showProducts(2)}</Tab.Panel>
        <Tab.Panel className="tabPanel">{showProducts(3)}</Tab.Panel>
      </Tab.Panels>
    </Tab.Group>
          </div>
    </section>
    </div>
  )
}


//  Backend Code

export const getServerSideProps = async () => {
  const categories = await fetchCategories();
  const products = await fetchProducts();
  return {
    props: {
      categories,
      products
    }, // will be passed to the page component as props
  }
}
/* 
3:57:44
https://tailwindcss.com/blog/automatic-class-sorting-with-prettier
https://headlessui.com/react/tabs
https://heroicons.com/
https://developers.remotebase.com/register
https://devdojo.com/tailwindcss/buttons
https://www.webtoons.com/en/

*/